repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-added-large-files
  - id: check-case-conflict
  - id: check-json
  - id: check-merge-conflict
  - id: check-yaml
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: pretty-format-json
    args: ["--autofix", "--no-sort-keys"]
  - id: trailing-whitespace

  - id: check-toml
  - id: check-xml
  - id: forbid-submodules
- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.33.3
  hooks:
  - id: check-github-workflows
  - id: check-renovate
  - id: check-jsonschema
    name: "Check Renovate default.json"
    files: ^default\.json$
    types: [json]
    args: ["--builtin-schema", "vendor.renovate"]

- repo: https://github.com/rhysd/actionlint
  rev: v1.7.7
  hooks:
  - id: actionlint

- repo: https://github.com/google/yamlfmt
  rev: v0.17.2
  hooks:
  - id: yamlfmt
- repo: https://github.com/andrewaylett/pre-commit-hooks
  rev: v0.7.0
  hooks:
  - id: init-hooks
- repo: https://github.com/editorconfig-checker/editorconfig-checker.python
  rev: 3.4.0
  hooks:
  - id: editorconfig-checker
    exclude: LICENSE

- repo: https://github.com/renovatebot/pre-commit-hooks
  rev: 41.85.0
  hooks:
  - id: renovate-config-validator
    args:
    - --strict
