name: CI
on: [push]
jobs:
  build:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    - uses: andrewaylett/pre-commit-action@e02b86d3d06c499827cc65aab7ceda1c609b0dd4 # v4
