name: CI
on: [push]
jobs:
  build:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: andrewaylett/pre-commit-action@74d6ae5219691d10674724f83249f248f1c47b1d # v4
