name: CI
on: [push]
jobs:
  build:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: andrewaylett/pre-commit-action@2f64e0a5efb9feb35024bb14b6591e31c6d30630 # v4
