on:
  workflow_dispatch:
  push:
    branches: [main]
    paths: [default.json]

jobs:
  tag:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: andrewaylett/pre-commit-action@2f64e0a5efb9feb35024bb14b6591e31c6d30630 # v4

    - name: Create tag
      id: tag
      run: |
        # Tag the version of the Renovate configuration
        set -euxo pipefail
        # Get the current release count
        git fetch --tags
        RELEASE_COUNT=$(git tag | grep -c "^v" || true | tr -d '\n')

        # Create and push the new tag with v prefix
        NEW_TAG="v$((RELEASE_COUNT + 1))"
        echo "Creating new tag: $NEW_TAG"
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git tag "$NEW_TAG"

        # Push both tags
        git push origin "$NEW_TAG"

        echo "new-tag=$NEW_TAG" >> "${GITHUB_OUTPUT}"

    - name: Release
      uses: softprops/action-gh-release@3d0d9888cb7fd7b750713d6e236d1fcb99157228 # v3.0.2
      with:
        tag_name: ${{ steps.tag.outputs.new-tag }}
        generate_release_notes: true
        make_latest: true
